expr_name: test
log_dir: ./logs             #log directory
device_num: 0
wandb: True

Environment:
  Entities:
    - entity_name: 'government'
      entity_args:
        n: 1            #number of government
        action_shape: 5

    - entity_name: 'household'
      entity_args:
        n: 100
        CRRA: 1
        IFE: 2
        eta: 0
        action_shape: 2
        e_p: 2.2e-6
        e_q: 0.990
        rho_e: 0.982
        sigma_e: 0.200
        super_e: 504.3

  env_core:
    possible_agents: ['government', 'households']
    env_args:
      tax_module: "ai_agent"
      alpha: 0.7445
      A: 10.
      year_per_step: 1
      depreciation_rate: 0.06
      consumption_tax_rate: 0.065
      interest_rate: 0.04
      gini_weight: 1
      gov_task: "gdp"  # choices: {"gdp", "gini", "social_welfare", "gdp_gini"}
      financial_crisis: False
      disasters: False


Trainer:
  n_households: 10
  log_std_min:  -20
  log_std_max:  2
  hidden_size:  128
  cuda: False
  q_lr: 3e-4
  p_lr: 3e-4
  buffer_size:  1e6
  env_name: 'wealth_distribution'
  init_exploration_policy:  'gaussian'
  n_epochs: 500
  epoch_length: 300
  update_cycles:  100
  target_update_interval: 1
  display_interval: 1
  batch_size: 128
  gamma: 0.975
  tau:  0.95
  eval_episodes: 5
  init_exploration_steps: 1000
  ppo_tau: 0.95
  ppo_gamma: 0.99
  eps: 1e-5
  update_epoch: 20
  clip: 0.1
  vloss_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 0.5
  update_freq: 2
  initial_train: 100
  noise_rate: 0.01
  epsilon: 0.1
  save_interval: 100
  house_alg: "real"
  gov_alg: "ippo"
  update_each_epoch: 100
  seed: 0
  wandb: False
  best_response: False
  entropy_coef: 0.025
  bc: False
  heterogeneous_house_agent: False
  heter_house_alg: "real"
  heter_house_rate: 0
  economic_shock: None  # 'disasters', 'financial_crisis',None






